from dataclasses import dataclass
from textwrap import dedent

from prinpy.interfaces import PrincipalCurve, CurveFitter, Projection
import numpy as np
from prinpy._utils import _check_shape

from typing import TYPE_CHECKING, Tuple

try:
    import torch
    from torch import nn

    _TORCH_AVAILABLE = True
except ImportError:
    _TORCH_AVAILABLE = False

if TYPE_CHECKING:
    import torch
    from torch import nn


if _TORCH_AVAILABLE:
    class _OrthogonalLoss(nn.Module):
        def __init__(self):
            super(_OrthogonalLoss, self).__init__()

        def forward(self, inputs: torch.Tensor, targets: torch.Tensor) -> torch.Tensor:
            # Compute the orthogonal loss as the mean squared distance from inputs to targets
            return torch.mean(torch.norm(inputs - targets, dim=1))


    class _NetworkCurveModel(nn.Module):
        def __init__(self, input_dim: int, hidden_dim: int):
            super(_NetworkCurveModel, self).__init__()
            self.encoder = nn.Sequential(
                nn.Linear(input_dim, hidden_dim),
                nn.Tanh(),
                nn.Linear(hidden_dim, 1),
            )
            self.decoder = nn.Sequential(
                nn.Linear(1, hidden_dim),
                nn.Tanh(),
                nn.Linear(hidden_dim, input_dim),
            )

        def forward(self, x: torch.Tensor) -> torch.Tensor:
            """Returns projection of x onto the curve."""
            return self.decoder(self.encoder(x))

        def encode(self, x: torch.Tensor) -> torch.Tensor:
            """Returns the projection layer output, which is the arc length."""
            return self.encoder(x)

        def decode(self, arc_length: torch.Tensor) -> torch.Tensor:
            """Returns the point on the curve corresponding to the given arc length."""
            return self.decoder(arc_length)


class _NetworkCurve(PrincipalCurve):
    """This class is a curve that is generated by a neural network. The project
    function will project the points to the curve generated by the fit function.

    Args:
        model (_NetworkCurveModel): The neural network model that generates the curve.
        min_arc (float): The minimum arc length of the curve, which corresponds to the 
            projection of the point on the curve that is closest to the data.
        max_arc (float): The maximum arc length of the curve, which corresponds to the 
            projection of the point on the curve that is farthest from the data.
    """

    def __init__(self, model: "_NetworkCurveModel", min_arc: float, max_arc: float):
        self._model = model
        self._min_arc = min_arc
        self._max_arc = max_arc

    @_check_shape(expected_dim=2)
    def project(self, X: np.ndarray) -> Projection:
        tensor_X = torch.tensor(X, dtype=torch.float32)
        pts = self._model.forward(tensor_X).detach().numpy()
        projection = self._model.encode(tensor_X).detach().numpy() - self._min_arc
        unit = projection / self.length()
        return Projection(points=pts, arc_lengths=projection, unit_lengths=unit)

    @_check_shape(expected_dim=1)
    def interpolate_from_length(self, X: np.ndarray) -> Projection:
        tensor_X = torch.tensor(X, dtype=torch.float32).reshape(-1, 1)
        pts = self._model.decode(tensor_X).detach().numpy()
        unit = X / self.length()
        return Projection(points=pts, arc_lengths=X, unit_lengths=unit)

    @_check_shape(expected_dim=1)
    def interpolate_from_unit(self, X: np.ndarray) -> Projection:
        arc_lengths = X * self.length() + self._min_arc
        tensor_X = torch.tensor(arc_lengths, dtype=torch.float32).reshape(-1, 1)
        pts = self._model.decode(tensor_X).detach().numpy()
        return Projection(points=pts, arc_lengths=arc_lengths, unit_lengths=X)

    def length(self) -> float:
        return self._max_arc - self._min_arc
    
    def control_points(self) -> np.ndarray:
        """Returns the control points of the curve, which are the decoded points at the min and max arc lengths."""
        with torch.no_grad():
            min_point = self._model.decode(torch.tensor([[self._min_arc]], dtype=torch.float32)).numpy()
            max_point = self._model.decode(torch.tensor([[self._max_arc]], dtype=torch.float32)).numpy()
        return np.vstack([min_point, max_point])


@dataclass(frozen=True)
class _TrainingRound:
    """A dataclass representing a training round for the NetworkFitter.

    Attributes:
        epoch (int): The current epoch number.
        loss (float): The loss value for the current epoch.
    """

    epoch: int
    loss: float

    def __str__(self):
        return f"Epoch: {self.epoch}, Loss: {self.loss:.4f}"


@dataclass(frozen=True)
class TrainingCallback:
    print_progress: bool = True
    every_n_epochs: int = 10

    def __call__(self, training_round: _TrainingRound):
        if self.print_progress and training_round.epoch % self.every_n_epochs == 0:
            print(training_round)


def _throw_need_torch():
    """Raises import error"""
    _err = """
    The NetworkFitter requires PyTorch to be installed. 
    Install via pip: pip install torch
    Or, reinstall prinpy with the 'neural' feature: pip install prinpy[neural]
    """
    raise ImportError(dedent(_err).strip())


class NetworkFitter(CurveFitter):
    """This class is a curve fitter that uses a neural network to fit a curve to
    the data. The fit function will create a model and fit it to the data, and
    the project function will project the data to the curve generated by the
    fit function. The projection index is given by the output of the
    intermediate layer of the model, which acts as the projection layer.
    """

    def __init__(
        self,
        dim: int,
        n_hidden: int,
        lr: float,
        epochs: int,
        callback: TrainingCallback | None = None,
    ):
        if not _TORCH_AVAILABLE:
            _throw_need_torch()

        self._model = _NetworkCurveModel(input_dim=dim, hidden_dim=n_hidden)
        self._lr = lr
        self._epochs = epochs
        self._callback = callback

    @_check_shape(expected_dim=2)
    def fit(self, data: np.ndarray) -> _NetworkCurve:
        data_t = torch.tensor(data, dtype=torch.float32)

        optimizer = torch.optim.Adam(self._model.parameters(), lr=self._lr)
        criterion = _OrthogonalLoss()

        for epoch in range(self._epochs):
            self._model.train()
            optimizer.zero_grad()
            outputs = self._model(data_t)
            loss = criterion.forward(outputs, data_t)
            loss.backward()
            optimizer.step()

            # Optionally, print the training progress
            if self._callback is not None:
                self._callback(_TrainingRound(epoch=epoch, loss=loss.item()))

        self._model.eval()
        min_arc, max_arc = self._find_arc_length(self._model, data)
        return _NetworkCurve(self._model, min_arc, max_arc)

    def _find_arc_length(
        self, model: "_NetworkCurveModel", data: np.ndarray
    ) -> Tuple[float, float]:
        """Find arc length. Run the data through and get the min and max of the projection layer."""
        with torch.no_grad():
            data_t = torch.tensor(data, dtype=torch.float32)
            projection_layer_output = model.encode(data_t).squeeze()
            min_arc = projection_layer_output.min().item()
            max_arc = projection_layer_output.max().item()
        return min_arc, max_arc
