from dataclasses import dataclass

import torch
from prinpy.interfaces import ICurve, ICurveFitter, Projection
from torch import nn
import numpy as np


class _OrthogonalLoss(nn.Module):
    def __init__(self):
        super(_OrthogonalLoss, self).__init__()

    def forward(self, inputs, targets):
        # Compute the orthogonal loss as the mean squared distance from inputs to targets
        return torch.mean(torch.norm(inputs - targets, dim=1))


class _NetworkCurveModel(nn.Module):
    def __init__(self, input_dim: int, hidden_dim: int):
        super(_NetworkCurveModel, self).__init__()
        self.encoder = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.Tanh(),
            nn.Linear(hidden_dim, 1),
        )
        self.decoder = nn.Sequential(
            nn.Linear(1, hidden_dim),
            nn.Tanh(),
            nn.Linear(hidden_dim, input_dim),
        )

    def forward(self, x):
        return self.decoder(self.encoder(x))

    def encode(self, x):
        return self.encoder(x)


class NetworkCurve(ICurve):
    """This class is a curve that is generated by a neural network. The project
    function will project the points to the curve generated by the fit function.
    """
    
    def __init__(self, model: _NetworkCurveModel):
        self.model = model

    def project(self, X: np.ndarray) -> Projection:
        raise NotImplementedError("Subclasses must implement this method")

    def interpolate_from_length(self, X: np.ndarray) -> Projection:
        raise NotImplementedError("Subclasses must implement this method")

    def interpolate_from_unit(self, X: np.ndarray) -> Projection:
        raise NotImplementedError("Subclasses must implement this method")

    def get_length(self) -> float:
        raise NotImplementedError("Subclasses must implement this method")

@dataclass(frozen=True)
class _TrainingRound:
    """A dataclass representing a training round for the NetworkFitter.

    Attributes:
        epoch (int): The current epoch number.
        loss (float): The loss value for the current epoch.
    """
    epoch: int
    loss: float

    def __str__(self):
        return f"Epoch: {self.epoch}, Loss: {self.loss:.4f}"

@dataclass(frozen=True)
class TrainingCallback:
    print_progress: bool = True
    every_n_epochs: int = 10

    def __call__(self, training_round: _TrainingRound):
        if self.print_progress and training_round.epoch % self.every_n_epochs == 0:
            print(training_round)

class NetworkFitter(ICurveFitter):
    """This class is a curve fitter that uses a neural network to fit a curve to
    the data. The fit function will create a model and fit it to the data, and
    the project function will project the data to the curve generated by the
    fit function. The projection index is given by the output of the
    intermediate layer of the model, which acts as the projection layer.
    """

    def __init__(self, dim: int, n_hidden: int, lr: float, epochs: int, callback: TrainingCallback | None = None):
        self.model = _NetworkCurveModel(input_dim=dim, hidden_dim=n_hidden)
        self.lr = lr
        self.epochs = epochs
        self.callback = callback

    def fit(self, data: np.ndarray) -> NetworkCurve:
        data_t = torch.tensor(data, dtype=torch.float32)

        optimizer = torch.optim.Adam(self.model.parameters(), lr=self.lr)
        criterion = _OrthogonalLoss()

        for epoch in range(self.epochs):
            self.model.train()
            optimizer.zero_grad()
            outputs = self.model(data_t)
            loss = criterion(outputs, data_t)
            loss.backward()
            optimizer.step()

            # Optionally, print the training progress
            if self.callback is not None:
                self.callback(_TrainingRound(epoch=epoch, loss=loss.item()))

        self.model.eval()
        return NetworkCurve(self.model)
