import numpy as np

def clpg(x: np.ndarray, tol: float) -> np.ndarray: ...
def clps(x: np.ndarray, tol: float) -> np.ndarray: ...

def find_nearest_points(data: np.ndarray, curve: np.ndarray) -> np.ndarray: ...